scraped_at: "2025-04-10T00:00:00+00:00"
source: "https://en.wikipedia.org/wiki/Nasdaq-100"
count: 30
tickers:
  - AAPL
  - ADBE
  - AMD
  - AMGN
  - AMZN
  - AVGO
  - BKNG
  - CDNS
  - CMCSA
  - COST
  - CRWD
  - CSCO
  - DXCM
  - GOOG
  - GOOGL
  - INTC
  - ISRG
  - LRCX
  - MELI
  - META
  - MNST
  - MSFT
  - NFLX
  - NVDA
  - PEP
  - PYPL
  - QCOM
  - SNPS
  - TSLA
  - ZS
